### ISSUE TITLE
babel 5 error

### ISSUE THREAD

**Issue by landabaso** [tappleby/redux-batched-subscribe#10]
Hi, I'm getting the following error when compiling a project with redux-batched-subscribe:

```
ERROR in ./~/redux-batched-subscribe/lib/index.js
Module build failed: ReferenceError: [BABEL] /MYPATH/node_modules/redux-batched-subscribe/lib/index.js: Using removed Babel 5 option: /MYPATH/node_modules/redux-batched-subscribe/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
```

Any idea? Thanks

**UPDATE:**

removing `redux-batched-subscribe/.babelrc` let me compile without errors.
Is it safe to remove it? In that case, should it be included in the npm package?

**Comment by tappleby** [comment]
Thanks. Published version 0.1.6 which uses a files whitelist instead of npmignore - 765bcf70af8c40952d1dee5ddcecb22b0907500b
