### ISSUE TITLE
usage with unstable_batchedUpdates

### ISSUE THREAD

**Issue by dannycochran** [tappleby/redux-batched-subscribe#25]
**Issue:**

I would think this code would batch dispatches together that occur synchronously:

```javascript
import { unstable_batchedUpdates } from 'react-dom';
import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import reducer from './reducer';

// this doesn't work as expected
export default createStore(
  reducer,
  compose(
    applyMiddleware(thunk),
    batchedSubscribe(unstable_batchedUpdates),
  ),
);
```

However, I'm noticing that each dispatch that fires outside of a React event causes a re-render, instead of one re-render once all synchronous dispatches have finished. If I swap out unstable_batchedUpdates for setTimeout, it works:

```javascript
// this works but is not ideal
export default createStore(
  reducer,
  compose(
    applyMiddleware(thunk),
    batchedSubscribe(setTimeout),
  ),
);
```

I think unstable_batchedUpdates used to work, is it possible it's failing with a newer version of react or redux?

**Env:**
```
  react: 16.3.0,
  redux: 4.0.0
```

**Comment by tappleby** [comment]
I believe `unstable_batchedUpdates` will only batch when triggered within a react lifecycle hook, which is only useful if you are triggering dispatches inside these hooks.

For more generic batching I recommend `debounce` or `defer` from lodash.
