### ISSUE TITLE
Combine batchedUpdates & requestAnimationFrame?

### ISSUE THREAD

**Issue by peteruithoven** [tappleby/redux-batched-subscribe#5]
As far as I understand React's batchedUpdates addon can batch multiple state updates into one render. It uses this internally automatically for DOM events (probably only the ones caused by React). By calling this manually you can include updates caused by events that are not automatically batched, like ajax requests and probably events triggered outside of React in general. 
This addon doesn't however work with requestAnimationFrame, which means you might have unnecessary rerenders in between frames. 
I understand they are working on always batching until animations frames and hoping they can release this soon.  

In the meantime it seems like a good idea to combine requestAnimationFrame with batchedUpdates. Did anyone already attempt this? 

More info: 
- http://fluxxor.com/guides/react.html
- http://www.simonkrueger.com/2015/11/06/Batch-Updating-In-React.html
- https://github.com/rackt/redux/issues/125
- Source: https://github.com/facebook/react/blob/0.14-stable/src/renderers/shared/reconciler/ReactUpdates.js

**Comment by peteruithoven** [comment]
We're now using: 
https://gist.github.com/peteruithoven/9a9363e064ee8bdf28ae

**Comment by tappleby** [comment]
:+1: thanks for sharing.
